### ISSUE TITLE
Trigger Deploy on Branch /v\d+\.\d+\$/

### ISSUE THREAD

**Issue by zixia** [Chatie/wechaty#956]
When we are developing on top of the master branch, we still need to make bug fixes for the stable branch.

Like we are developing v0.13.x now, and we are maintaining the version of v0.12.x, which is a branch for the stable version, named `v0.12`.

1. TravisCI for publishing NPM
1. CircleCI for rebuilding Docker Image

See: 
1. Build Stages: Deploying to npm - https://docs.travis-ci.com/user/build-stages/deploy-npm/

**Comment by zixia** [comment]
done.

```
stages:
  - test
  - pack
  - name: deploy
    if: branch = /^(master|v\d+\.\d+)/
```
